In [26]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns

In [27]:
df = pd.read_csv("../data/raw/venta_idealista.csv",on_bad_lines="warn")
df.head()

C:\Users\PDE6221\AppData\Local\Temp\ipykernel_25712\2889665582.py:1: ParserWarning: Skipping line 38: expected 22 fields, saw 23

  df = pd.read_csv("../data/raw/venta_idealista.csv",on_bad_lines="warn")

,id_anuncio,fuente,operacion,tipo_inmueble,subtipo,direccion_texto,barrio_zona,municipio,provincia,precio_eur,...,descuento_pct,garaje_incluido,habitaciones,superficie_m2,planta,exterior,ascensor,obra_nueva_categoria,obra_nueva_flag,notas_parseo
1,Inmobiliaria E-Castro,venta,piso,NaN,"""Avenida Riomar","1""",Cotolino,Castro-Urdiales,Cantabria,498000,...,NaN,sí,4,121,4,sí,sí,otros,0,NaN
2,Inmobiliarias.com,venta,casa,chalét independiente,"Barrio Brazomar, 46",Cotolino,Castro-Urdiales,Cantabria,575000,NaN,...,sí,5,232,NaN,desconocido,desconocido,otros,0,NaN,NaN
3,Inmobiliaria E-Castro,venta,piso,NaN,"""Calle Leonardo Rucabado","6""",Centro,Castro-Urdiales,Cantabria,299000,...,NaN,desconocido,2,84,3,sí,sí,otros,0,Garaje no indicado
4,Inmobiliaria E-Castro,venta,piso,NaN,"""Calle de la Ronda","32""",Centro,Castro-Urdiales,Cantabria,340000,...,NaN,desconocido,4,99,5,sí,sí,otros,0,Garaje no indicado
5,Inmobiliaria E-Castro,venta,casa,chalét independiente,Barrio Sámano,Sámano,Castro-Urdiales,Cantabria,799000,NaN,...,sí,5,511,NaN,desconocido,desconocido,otros,0,Dirección sin número,NaN

In [28]:

cols_bool = [
    "ascensor",
    "exterior",
    "garaje_incluido",
]

for col in cols_bool:
    df[col] = (
        df[col]
            .astype(str)
            .str.strip()
            .str.lower()
            .replace({
                "desconocido": np.nan,
                "sí": 1,
                "si": 1,
                "no": 0
            })
    )

    # asegurar tipo numérico
    df[col] = pd.to_numeric(df[col], errors="coerce")

In [29]:
df["descuento_flag"] = df["descuento_pct"].notna().astype(int)

In [30]:
df["planta"] = df["planta"].replace({"bajo": 0, "Bajo": 0})
df["planta"] = pd.to_numeric(df["planta"], errors="coerce")

In [31]:
df["tipo_inmueble"] = df["tipo_inmueble"].str.lower().str.strip()
df["subtipo"] = df["subtipo"].str.lower().str.strip()

In [32]:
valores_eliminar = [
    "finca",
    "finca_rustica",
    "garaje",
    "garaje/local",
    "piso/casa",
    "edificio"
]

df = df[~df["tipo_inmueble"].isin(valores_eliminar)]

In [33]:
mask_duplex_atico = df["tipo_inmueble"].isin(["dúplex", "duplex", "ático", "atico"])

df.loc[mask_duplex_atico, "subtipo"] = df.loc[mask_duplex_atico, "tipo_inmueble"]

df.loc[mask_duplex_atico, "tipo_inmueble"] = "piso"

In [34]:
df["tipo_inmueble"] = df["tipo_inmueble"].replace({
    "chalet": "casa"
})

In [35]:
mask_piso_sin_subtipo = (
    (df["tipo_inmueble"] == "piso") &
    (~df["subtipo"].isin(["dúplex", "duplex", "ático", "atico"]))
)

df.loc[mask_piso_sin_subtipo, "subtipo"] = "apartamento"

In [36]:
df["subtipo"].unique()

array(['"avenida riomar', 'barrio brazomar, 46',
       '"calle leonardo rucabado', '"calle de la ronda', 'barrio sámano',
       '"calle de angel perez hornoas cholo"', '"calle de la granja"',
       '"calle ataúlfo argenta"', 'barrio montealegre',
       '"isaac castillo"', '"calle doctor marañón"',
       '"avenida manuel garcía lago"', '"calle leonardo rucabado"',
       'barrio cerdigo', '"avenida maura"', '"avenida de cantabria"',
       'calle del alto de la cruz', '"paseo de pereda"',
       'barrio la arnía', '"avenida de pontejos"',
       '"calle juan de herrera"', '"calle belén', 'barrio sámano, 40',
       'calle aureliano linares rivas',
       'calle aureliano linares rivas, 17', 'calle paco labiano, 5',
       'avenida de chinchapapa', 'calle teresa de calcuta',
       'avenida de francia', 'centro', 'calle padre ignacio ellacuría',
       'el puntal', 'zona playa', 'plaza marqués de albaida',
       'calle peredo y nogales', 'avenida de la libertad, 87',
       'avenida los caleros', 'oriñón-allendagua',
       'calle juan josé pérez del molino', 'barrio sámano-vallegón 1',
       'barrio mellin samano, s/n', 'ataulfo argenta 5',
       'calle república argentina 5', 'cerrillo sámano',
       'barrio sámano-helguera', 'calle república de chile',
       'calle doctor senderos', 'calle república de colombia',
       'calle marqués de comillas', 'calle república de costa rica',
       'calle república de guatemala', 'avenida de la libertad',
       'calle general moscardó', 'calle tetuán', 'calle los nogales',
       'calle duque de ahumada 9', 'camino derecha, 27 -13',
       'calle san marcial, 23', 'calle isaac peral',
       'calle san celedonio', 'av cantabria',
       'calle ataulfo argenta músico', 'calle justicia',
       'calle francisco de quevedo', 'el sardinero', 'montesolmar, 22',
       'calle república argentina 9', 'barrio brazomar', 'islares',
       'calle ontanilla 6', 'calle calderón de la barca',
       'residencial los arces', 'paseo de trengandín',
       'urbanización la mina', 'ayuntamientos democraticos',
       'calle bajada del chorrillo 8', 'calle marqués de la hermida 72',
       'el parque - zapatón', 'paseo menéndez pelayo',
       'barrio la soledad', 'valdenoja', 'onton, s/n', 'calle el sable 8',
       'alisal - cazoña - san román', 'paseo ocharan mazas',
       'calle el hoyo 5', 'carretera mioño', 'menendez pelayo',
       'barrio de santullán', 'calle san andrés 8', 'calle santander',
       'barrio otañes', 'calle de silvestre ochoa',
       'calle venancio bosco', 'calle de la ronda 3', 'subida a cueto',
       'barrio otañes, 77', 'pozo barrio el', 'ca-520', 'barrio oriñón',
       'calle la rúa', 'calle san andrés', 'calle ataúlfo argenta',
       'calle padre basabe', 'calle el hoyo', 'direccion_texto',
       'calle de montecerredo', 'calle miguel de cervantes',
       'calle los caserios', 'calle santa ana',
       'calle bajada del chorrillo', 'barrio islares', 'playa ostende',
       'barrio allendelagua, 30', 'bajada de la encina', 'calle bonifaz',
       'calle emperador', 'francia 18', 'avenida de españa',
       'calle lope de vega 18', 'calle las rederas',
       'calle el millajo, 1469', 'calle vargas',
       'calle del voluntariado 6', 'calle castelar',
       'calle joaquín bustamante 6', 'calle república de panamá, 26',
       'calle real racing club', 'calle bajada del chorrillo 3',
       'calle de la ronda 18', 'dúplex', 'calle los pinares',
       'isaac castillo', 'calle alta 24', 'calle san sebastian',
       'calle poeta gerardo diego', 'via cornelia 28', 'barrio mioño',
       'calle lauro fernández gonzález', 'calle jorge sepúlveda',
       'numancia - san fernando', 'calle río de la pila',
       'calle la amistad', 'calle francisco palazuelos',
       'calle casimiro sainz', 'calle francisco tomás y valiente',
       'samano', 'calle de san juan', 'calle gutiérrez rada',
       'calle castrejón', 'avenida ris', 'calle victoria',
       'calle manuel gonzález hoyos', 'calle padre pedro lópez',
       'calle hermanos calderón', 'calle luis martínez',
       'mioño-santullán', 'urbanización ría del pas',
       'barrio las carcobas', 'avenida de valdecilla', 'liencres',
       'calle maría cristina', 'peñacastillo - nuevamontaña',
       'calle santa lucía', 'parbayón', 'calle eusebio santamaría',
       'castilla - hermida', 'calle la llanilla', 'calle leopoldo pardo',
       'calle vicente trueba 3', 'avenida de cantabria', 'barrio huyo',
       'avenida del faro', 'barrio las cerreas', 'calle los indianos',
       'barrio la sierra 38', 'barrio cereceda 11', 'calle monte',
       'calle castío', 'calle san pedro', 'calle castilla',
       'barcena de cicero', 'calle marqués de la hermida', 'limpias',
       'ampuero', 'calle el casar', 'barrio el albulde', 'colindres',
       'calle los foramontanos', 'escobedo', 'calle francisco de cáceres',
       'abra del pas', 'avenida benedicto ruiz', 'calle de la arnia',
       'guriezo', 'voto', 'calle los calderones', 'calle el cormecio',
       'avenida españa', 'calle el cabrahido', 'santoña', 'calle espina',
       'barrio la quintana', 'travesía de el cantón 22',
       'barrio secadura-la fragua 69 a', 'barrio villanueva 39',
       'la concha 6', 'barrio las cuartas', 'hoznayo',
       'calle menéndez pelayo', 'paseo de altamira 12', 'barrio rodil',
       'barrio entrambasaguas', 'la bárcena 8', 'calle doctor senderos 5',
       'barrio la iglesia', 'calle veridiano rojo herrera 7',
       'barrio ontón', 'calle francisco cubría', 'calle higarino 443',
       'avenida santander 16', 'calle el mazo de abajo', 'calle galicia',
       'calle del progreso 2', 'calle torrelavega', 'barrio requejada',
       'barrio la cotera', 'calle lluja', 'calle calvo sotelo',
       'barrio villanueva', 'puente barrio el',
       'el callejo - la pesquera - la arenosa', 'avenida la constitución',
       'calle el millajo', 'avenida de pontejos', 'barrio rioseco',
       'liérganes', 'urbanización virgen del mar', 'calle prosperidad',
       'barrio viveda', 'barrio la portilla', 'calle río saja 24',
       'calle teresa de calcuta 14', 'calle torrelavega 6',
       'calle arrabal', 'barrio la estación', 'calle muelle del rey',
       'calle las peñias 6', 'avenida san miguel 25',
       'calle san juan bautista de la salle', 'barrio solegrario',
       'calle la ojerada', 'calle simancas', 'barrio la puntania',
       'jan curtius 17', 'carretera avios 30', 'av fernando saiz',
       'carretera trasculina 6', 'calle valladolid 3', 'calle burgos',
       'barrio carrejo', 'urbanización peñaflor', 'calle gerardo diego',
       'calle ortiz otáñez 32', 'barrio villaparte', 'carretera ongayo',
       'ca-303', 'calle carlos iii', 'barrio la somadilla',
       'barrio la esprilla', 'calle alday', 'av benedicto ruiz',
       'la tejera', 'barrio mies del valle', 'barrio san mames iglesia',
       'calle república argentina', 'n-611', 'calle la mies 7',
       'bo liaño-bofetán', 'ribamontan al monte', 'barrio la sierra 1',
       'tregadín', 'rasines', 'calle playa de usil 465',
       'avenida san miguel 1', 'barrio abaño 3', 'brazomar',
       'barrio castillo', 'barrio casuso', 'calle alonso del camino',
       'barrio el mesón', 'bezana', 'carretera de soano',
       'barrio el carmen 40', 'barrio arnuero-espinamonte',
       'barrio la iglesia de san mamés', 'calle san luis',
       'lugar padierniga', 'barrio el callejo', 'camargo',
       'calle la tabierna 47', 'barrio la sierra 61', 'puente san miguel',
       'barrio san pantaleón', 'calle manuel gonzález hoyos 6',
       'calle río saja', 'calle carnerizas', 'ajo', 'ático', 'polanco',
       'entrambasaguas', 'el astillero', 'galizano', 'arenas de iguña',
       'marina de cudeyo', 'torrelavega', 'cuatro caminos', 'ris',
       'centro - ayuntamiento', 'laredo', 'noja',
       'calle juan jose ruano 18', 'maoño', 'ramales de la victoria',
       'alfoz de lloredo', 'igollo', 'suesa', 'calle manzanedo 35',
       'penagos', 'oruña', 'suances', 'cotolino', 'barrio baltezana',
       'fernando de los ríos', 'mortera', 'oriñón',
       'paseo de la barquera 53 a', 'calle santa teresa', 'barrio dueso',
       'plaza san antonio', 'calle barrio el mazo 14',
       'calle de san martín 6', 'calle camus 83', 'barrio la braña 1',
       'calle bo samano-helguera 205', 'barrio labarces', 'ca-260 42',
       'cl francisco tomas valiente', 'calle antonio de la dehesa 7',
       'barrio pondrá', 'avenida de berria primera avenida',
       'barrio el puerto', 'barrio el mazo',
       'avenida playa san juan de la canal', 'calle san roque',
       'camino vial', 'calle padre ángel 10', 'calle santander 4',
       'calle herminio fernández caballero', 'calle la fábrica',
       'calle monasterio 9', 'calle el pelegrín', 'barrio gama 25 b',
       'bárcena de cicero', 'calle joaquin fernandez san emeterio 14',
       'avenida solvay', 'liendo', 'calle jorge sepúlveda 16', 'ruiloba',
       'barrio los corrales', 'diseminado hazas cesto 1001',
       'avenida derechos humanos 3', 'calle barrio la torre 17',
       'calle justicia 2', 'barrio el carite 11', 'barrio la rasa 4',
       'calle las casillas', 'calle libertad 3', 'barrio bárcena',
       'calle de navajeda', 'calle aviche 25',
       'calle doctor antonio ruiz ruiz', 'calle emperador carlos v',
       'calle pintor varela 29', 'calle serapio beade 9',
       'barrio balbacienta', 'calle ernest lluch 36', 'barrio san mateo',
       'calle barrio de santullán 39',
       'calle hermandad donantes de sangre', 'barrio rioseco 4',
       'barrio el hacha', 'barrio la arenosa', 'barrio los valles',
       'barrio la pesquera', 'calle rebollar', 'avenida derechos humanos',
       'calle eulogio fernández barros',
       'avenida francisco giner de los ríos',
       'travesía los derechos humanos 13', 'calle maza 9',
       'barrio arnuero 1', 'barrio el monte s/n', 'calle ría de solía',
       'barrio valledal', 'cl pielagos', 'valdaliga', 'calle adarzo 63',
       'barrio la pelia', 'avenida pérez galdós', 'barrio rioseco 29 a',
       'barrio agüeras', 'calle fuente vieda 906', 'barrio brazomar 54',
       'calle san josé 17', 'calle marcelino sanz de sautuola 14',
       'ps general dávila', 'cl ruamayor', 'barrio bustillo 1',
       'barrio laiseca 162', 'barrio cerecedas',
       'calle sor maría del carmen', 'calle jaime del amo',
       'calle san lorenzo', 'avenida josé maría de pereda 38',
       'calle la mies', 'barrio el puente 17', 'calle san fernando 22',
       'calle río arriba 315',
       'paseo general dávila - grupo san francisco 294',
       'calle francisco de cáceres 2', 'calle igareda',
       'barrio la barquería', 'calle padre antonio 24', 'bo. liaño s/n',
       'calle victoriano fernández 16', 'ds. roiz s/n',
       'calle carlos haya 11', 'calle piedra del cormorán',
       'barrio pomar 7', 'calle rosalía de castro 25', 'rioseco',
       'barrio llueva-arriba', 'calle adal treto', 'calle paco labiano',
       'calle palacio', 'calle carral', 'calle río',
       'calle serafín escalante', 'balbacienta',
       'calle amador de los ríos', 'calle requejada', nan,
       'calle la braña', 'barrio san pedro', 'calle enrique gran',
       'barrio la peña', 'calle barrio la', 'calle del progreso',
       'travesía de el cantón', 'avenida conde de albox',
       'barrio la puntania 45', 'plaza campo de las ferias',
       'calle la bolera', 'calle valladolid', 'calle el carmen',
       'avenida primera avenida', 'calle la quinta',
       'calle m ruiz arenado', 'barrio el pino',
       'urbanización rìa del pas', 'calle murillo', 'calle el peñon s/n',
       'barrio las reigadas', 'camino mortera a liencres',
       'barrio sorriba', 'barrio la piñera 3', 'urbanización la gruta 7',
       'av mompia', 'barrio somacueto', 'avenida josé maría de pereda',
       'calle respuela 2', 'calle s cruz-san juan 7', 'barrio la cruz',
       'la calleja', 'barrio portio', 'avenida josé maría de pereda 8',
       'barrio el pozo de la torre 1a', 'barrio el pozo de la torre 1',
       'calle barrio el pozo de la torre 1 distrito mortera 1',
       'avenida josé maría de pereda 6',
       'vía barrio el pozo de la torre 1', 'cl respuela 4',
       'avenida marqués de valdecilla', 'alto san mateo s/n',
       'barrio la cotera 1', 'calle bo las reigadas 12',
       'urbanización ladera sur', 'av san juan de la canal 85',
       'avenida marqués de valdecilla s/n', 'parcela b19',
       'calle el palacio s/n', 'barrio la caseta',
       'urbanización el padrón 1', 'calle la llata', 'cl llata (la)',
       'barrio salas', 'barrio de la cruz s/n',
       'urb. cierro de la sara s/n', 'barrio el dueso',
       'soto de la marina', 'avenida mompía', 'barrio somacueto 4a',
       'calle el sartal', 'avenida s cibrian', 'barrio la piñera 5',
       'bo llatas 1010', 'urbanización arco iris', 'barrio manzanedo',
       'boo', 'avenida menéndez pelayo', 'calle la gesa 6',
       'calle murillo 1', 'jose maria pereda', 'calle ramón ramírez',
       'avenida menéndez pelayo 11', 'barrio san josé', 'calle respuela',
       'marina sport 5', 'avenida josé maría de pereda 12',
       'urbanización la roca', 'barrio san josé 2', 'barrio la piñera 16',
       'sancibrián', 'bezana 1', 'calle de borrancho', 'respuela 4',
       'calle mies de domañas 98', 'calle gertrudis gómez avellaned 1',
       'calle san felipe neri 49', 'calle la fuente 2',
       'hermanos calderón 20', 'calle bellavista 5', 'calle udial 1',
       'calle gertrudis gómez 5', 'bº argomilla 5',
       'avenida monseñor del val 13', 'carretera ca-135 6',
       'calle mies de domañas 132', 'alto de pedroa s/n',
       'calle cam. del bao 2', 'calle joaquín fernández san emeterio 14',
       'bo. quintana 268', 'calle ojáiz s/n', 'calle manel vélez 14',
       'vía barrio el canal 14', 'avenida de cantabria 60', 'general 181',
       'calle mijares 21', 'manuel vélez 10', 'josé ortega y gasset 39',
       'calle la central 21', 'calle el millajo 46', 'barrio casar 253',
       'avenida joaquín ortiz de zárate 99',
       'calle de victoriano fernández 16', 'calle aldea 24',
       'calle carmen bravo villasante / calle santiago garcía cuadrado 3',
       'calle ricardo bernardo 1', 'calle castío 1',
       'calle menéndez pelayo 13', 'la hayuela s/n',
       'calle piedra del cormorán s/n', 'calle el peñón s/n',
       'avenida alfonso viii s/n', 'ayuntamientos democráticos 46',
       'joaquín ferna 1', 'barrio requejada 33', 'calle alcarite s/n',
       'calle torres quevedo 7', 'calle abad paterno 18',
       'barrio la canal 15', 'calle consolación 24', 'calle la central 1',
       'calle barrio el pozo de la torre 1, distrito mortera 1',
       'calle barrio yuso 10', 'paseo de la barquera 53a', 'calle aro 3',
       'calle de la maza 9', 'lugar barrio bádames 1018',
       'calle san juan 7', 'calle bo sámano-helguera 205',
       'los tranquilos 3', 'avenida de españa 29',
       'vía barrio brazomar 36', 'calle jaime del amo 8',
       'calle josé posada herrera 10', 'barrio islares 41',
       'calle barrio las escuelas 35', 'calle pedro sobrado pintor s/n',
       'barrio la rañada 14', 'calle la central 4', 'calle bº ladredo 75',
       'calle barrio bolado 8', 'bº cubas 18',
       'calle padre ignacio ellacuría 163', 'ernest lluch s/n'],
      dtype=object)

In [37]:
df["subtipo"] = (
    df["subtipo"]
        .str.lower()
        .str.strip()
        .replace({
            "chalét independiente": "casa independiente",
            "chalét pareado": "casa adosada",
            "chalet pareado": "casa adosada",
            "chalét adosado": "casa adosada",
            "chalet adosado": "casa adosada",
            "casa o chalet independiente": "casa independiente",
            "casa o chalet independent\ufeffe": "casa independiente",
            "chalet": "casa independiente",
            "casa unifamiliar": "casa independiete"
        })
)

In [38]:
df["subtipo"].unique()

array(['"avenida riomar', 'barrio brazomar, 46',
       '"calle leonardo rucabado', '"calle de la ronda', 'barrio sámano',
       '"calle de angel perez hornoas cholo"', '"calle de la granja"',
       '"calle ataúlfo argenta"', 'barrio montealegre',
       '"isaac castillo"', '"calle doctor marañón"',
       '"avenida manuel garcía lago"', '"calle leonardo rucabado"',
       'barrio cerdigo', '"avenida maura"', '"avenida de cantabria"',
       'calle del alto de la cruz', '"paseo de pereda"',
       'barrio la arnía', '"avenida de pontejos"',
       '"calle juan de herrera"', '"calle belén', 'barrio sámano, 40',
       'calle aureliano linares rivas',
       'calle aureliano linares rivas, 17', 'calle paco labiano, 5',
       'avenida de chinchapapa', 'calle teresa de calcuta',
       'avenida de francia', 'centro', 'calle padre ignacio ellacuría',
       'el puntal', 'zona playa', 'plaza marqués de albaida',
       'calle peredo y nogales', 'avenida de la libertad, 87',
       'avenida los caleros', 'oriñón-allendagua',
       'calle juan josé pérez del molino', 'barrio sámano-vallegón 1',
       'barrio mellin samano, s/n', 'ataulfo argenta 5',
       'calle república argentina 5', 'cerrillo sámano',
       'barrio sámano-helguera', 'calle república de chile',
       'calle doctor senderos', 'calle república de colombia',
       'calle marqués de comillas', 'calle república de costa rica',
       'calle república de guatemala', 'avenida de la libertad',
       'calle general moscardó', 'calle tetuán', 'calle los nogales',
       'calle duque de ahumada 9', 'camino derecha, 27 -13',
       'calle san marcial, 23', 'calle isaac peral',
       'calle san celedonio', 'av cantabria',
       'calle ataulfo argenta músico', 'calle justicia',
       'calle francisco de quevedo', 'el sardinero', 'montesolmar, 22',
       'calle república argentina 9', 'barrio brazomar', 'islares',
       'calle ontanilla 6', 'calle calderón de la barca',
       'residencial los arces', 'paseo de trengandín',
       'urbanización la mina', 'ayuntamientos democraticos',
       'calle bajada del chorrillo 8', 'calle marqués de la hermida 72',
       'el parque - zapatón', 'paseo menéndez pelayo',
       'barrio la soledad', 'valdenoja', 'onton, s/n', 'calle el sable 8',
       'alisal - cazoña - san román', 'paseo ocharan mazas',
       'calle el hoyo 5', 'carretera mioño', 'menendez pelayo',
       'barrio de santullán', 'calle san andrés 8', 'calle santander',
       'barrio otañes', 'calle de silvestre ochoa',
       'calle venancio bosco', 'calle de la ronda 3', 'subida a cueto',
       'barrio otañes, 77', 'pozo barrio el', 'ca-520', 'barrio oriñón',
       'calle la rúa', 'calle san andrés', 'calle ataúlfo argenta',
       'calle padre basabe', 'calle el hoyo', 'direccion_texto',
       'calle de montecerredo', 'calle miguel de cervantes',
       'calle los caserios', 'calle santa ana',
       'calle bajada del chorrillo', 'barrio islares', 'playa ostende',
       'barrio allendelagua, 30', 'bajada de la encina', 'calle bonifaz',
       'calle emperador', 'francia 18', 'avenida de españa',
       'calle lope de vega 18', 'calle las rederas',
       'calle el millajo, 1469', 'calle vargas',
       'calle del voluntariado 6', 'calle castelar',
       'calle joaquín bustamante 6', 'calle república de panamá, 26',
       'calle real racing club', 'calle bajada del chorrillo 3',
       'calle de la ronda 18', 'dúplex', 'calle los pinares',
       'isaac castillo', 'calle alta 24', 'calle san sebastian',
       'calle poeta gerardo diego', 'via cornelia 28', 'barrio mioño',
       'calle lauro fernández gonzález', 'calle jorge sepúlveda',
       'numancia - san fernando', 'calle río de la pila',
       'calle la amistad', 'calle francisco palazuelos',
       'calle casimiro sainz', 'calle francisco tomás y valiente',
       'samano', 'calle de san juan', 'calle gutiérrez rada',
       'calle castrejón', 'avenida ris', 'calle victoria',
       'calle manuel gonzález hoyos', 'calle padre pedro lópez',
       'calle hermanos calderón', 'calle luis martínez',
       'mioño-santullán', 'urbanización ría del pas',
       'barrio las carcobas', 'avenida de valdecilla', 'liencres',
       'calle maría cristina', 'peñacastillo - nuevamontaña',
       'calle santa lucía', 'parbayón', 'calle eusebio santamaría',
       'castilla - hermida', 'calle la llanilla', 'calle leopoldo pardo',
       'calle vicente trueba 3', 'avenida de cantabria', 'barrio huyo',
       'avenida del faro', 'barrio las cerreas', 'calle los indianos',
       'barrio la sierra 38', 'barrio cereceda 11', 'calle monte',
       'calle castío', 'calle san pedro', 'calle castilla',
       'barcena de cicero', 'calle marqués de la hermida', 'limpias',
       'ampuero', 'calle el casar', 'barrio el albulde', 'colindres',
       'calle los foramontanos', 'escobedo', 'calle francisco de cáceres',
       'abra del pas', 'avenida benedicto ruiz', 'calle de la arnia',
       'guriezo', 'voto', 'calle los calderones', 'calle el cormecio',
       'avenida españa', 'calle el cabrahido', 'santoña', 'calle espina',
       'barrio la quintana', 'travesía de el cantón 22',
       'barrio secadura-la fragua 69 a', 'barrio villanueva 39',
       'la concha 6', 'barrio las cuartas', 'hoznayo',
       'calle menéndez pelayo', 'paseo de altamira 12', 'barrio rodil',
       'barrio entrambasaguas', 'la bárcena 8', 'calle doctor senderos 5',
       'barrio la iglesia', 'calle veridiano rojo herrera 7',
       'barrio ontón', 'calle francisco cubría', 'calle higarino 443',
       'avenida santander 16', 'calle el mazo de abajo', 'calle galicia',
       'calle del progreso 2', 'calle torrelavega', 'barrio requejada',
       'barrio la cotera', 'calle lluja', 'calle calvo sotelo',
       'barrio villanueva', 'puente barrio el',
       'el callejo - la pesquera - la arenosa', 'avenida la constitución',
       'calle el millajo', 'avenida de pontejos', 'barrio rioseco',
       'liérganes', 'urbanización virgen del mar', 'calle prosperidad',
       'barrio viveda', 'barrio la portilla', 'calle río saja 24',
       'calle teresa de calcuta 14', 'calle torrelavega 6',
       'calle arrabal', 'barrio la estación', 'calle muelle del rey',
       'calle las peñias 6', 'avenida san miguel 25',
       'calle san juan bautista de la salle', 'barrio solegrario',
       'calle la ojerada', 'calle simancas', 'barrio la puntania',
       'jan curtius 17', 'carretera avios 30', 'av fernando saiz',
       'carretera trasculina 6', 'calle valladolid 3', 'calle burgos',
       'barrio carrejo', 'urbanización peñaflor', 'calle gerardo diego',
       'calle ortiz otáñez 32', 'barrio villaparte', 'carretera ongayo',
       'ca-303', 'calle carlos iii', 'barrio la somadilla',
       'barrio la esprilla', 'calle alday', 'av benedicto ruiz',
       'la tejera', 'barrio mies del valle', 'barrio san mames iglesia',
       'calle república argentina', 'n-611', 'calle la mies 7',
       'bo liaño-bofetán', 'ribamontan al monte', 'barrio la sierra 1',
       'tregadín', 'rasines', 'calle playa de usil 465',
       'avenida san miguel 1', 'barrio abaño 3', 'brazomar',
       'barrio castillo', 'barrio casuso', 'calle alonso del camino',
       'barrio el mesón', 'bezana', 'carretera de soano',
       'barrio el carmen 40', 'barrio arnuero-espinamonte',
       'barrio la iglesia de san mamés', 'calle san luis',
       'lugar padierniga', 'barrio el callejo', 'camargo',
       'calle la tabierna 47', 'barrio la sierra 61', 'puente san miguel',
       'barrio san pantaleón', 'calle manuel gonzález hoyos 6',
       'calle río saja', 'calle carnerizas', 'ajo', 'ático', 'polanco',
       'entrambasaguas', 'el astillero', 'galizano', 'arenas de iguña',
       'marina de cudeyo', 'torrelavega', 'cuatro caminos', 'ris',
       'centro - ayuntamiento', 'laredo', 'noja',
       'calle juan jose ruano 18', 'maoño', 'ramales de la victoria',
       'alfoz de lloredo', 'igollo', 'suesa', 'calle manzanedo 35',
       'penagos', 'oruña', 'suances', 'cotolino', 'barrio baltezana',
       'fernando de los ríos', 'mortera', 'oriñón',
       'paseo de la barquera 53 a', 'calle santa teresa', 'barrio dueso',
       'plaza san antonio', 'calle barrio el mazo 14',
       'calle de san martín 6', 'calle camus 83', 'barrio la braña 1',
       'calle bo samano-helguera 205', 'barrio labarces', 'ca-260 42',
       'cl francisco tomas valiente', 'calle antonio de la dehesa 7',
       'barrio pondrá', 'avenida de berria primera avenida',
       'barrio el puerto', 'barrio el mazo',
       'avenida playa san juan de la canal', 'calle san roque',
       'camino vial', 'calle padre ángel 10', 'calle santander 4',
       'calle herminio fernández caballero', 'calle la fábrica',
       'calle monasterio 9', 'calle el pelegrín', 'barrio gama 25 b',
       'bárcena de cicero', 'calle joaquin fernandez san emeterio 14',
       'avenida solvay', 'liendo', 'calle jorge sepúlveda 16', 'ruiloba',
       'barrio los corrales', 'diseminado hazas cesto 1001',
       'avenida derechos humanos 3', 'calle barrio la torre 17',
       'calle justicia 2', 'barrio el carite 11', 'barrio la rasa 4',
       'calle las casillas', 'calle libertad 3', 'barrio bárcena',
       'calle de navajeda', 'calle aviche 25',
       'calle doctor antonio ruiz ruiz', 'calle emperador carlos v',
       'calle pintor varela 29', 'calle serapio beade 9',
       'barrio balbacienta', 'calle ernest lluch 36', 'barrio san mateo',
       'calle barrio de santullán 39',
       'calle hermandad donantes de sangre', 'barrio rioseco 4',
       'barrio el hacha', 'barrio la arenosa', 'barrio los valles',
       'barrio la pesquera', 'calle rebollar', 'avenida derechos humanos',
       'calle eulogio fernández barros',
       'avenida francisco giner de los ríos',
       'travesía los derechos humanos 13', 'calle maza 9',
       'barrio arnuero 1', 'barrio el monte s/n', 'calle ría de solía',
       'barrio valledal', 'cl pielagos', 'valdaliga', 'calle adarzo 63',
       'barrio la pelia', 'avenida pérez galdós', 'barrio rioseco 29 a',
       'barrio agüeras', 'calle fuente vieda 906', 'barrio brazomar 54',
       'calle san josé 17', 'calle marcelino sanz de sautuola 14',
       'ps general dávila', 'cl ruamayor', 'barrio bustillo 1',
       'barrio laiseca 162', 'barrio cerecedas',
       'calle sor maría del carmen', 'calle jaime del amo',
       'calle san lorenzo', 'avenida josé maría de pereda 38',
       'calle la mies', 'barrio el puente 17', 'calle san fernando 22',
       'calle río arriba 315',
       'paseo general dávila - grupo san francisco 294',
       'calle francisco de cáceres 2', 'calle igareda',
       'barrio la barquería', 'calle padre antonio 24', 'bo. liaño s/n',
       'calle victoriano fernández 16', 'ds. roiz s/n',
       'calle carlos haya 11', 'calle piedra del cormorán',
       'barrio pomar 7', 'calle rosalía de castro 25', 'rioseco',
       'barrio llueva-arriba', 'calle adal treto', 'calle paco labiano',
       'calle palacio', 'calle carral', 'calle río',
       'calle serafín escalante', 'balbacienta',
       'calle amador de los ríos', 'calle requejada', nan,
       'calle la braña', 'barrio san pedro', 'calle enrique gran',
       'barrio la peña', 'calle barrio la', 'calle del progreso',
       'travesía de el cantón', 'avenida conde de albox',
       'barrio la puntania 45', 'plaza campo de las ferias',
       'calle la bolera', 'calle valladolid', 'calle el carmen',
       'avenida primera avenida', 'calle la quinta',
       'calle m ruiz arenado', 'barrio el pino',
       'urbanización rìa del pas', 'calle murillo', 'calle el peñon s/n',
       'barrio las reigadas', 'camino mortera a liencres',
       'barrio sorriba', 'barrio la piñera 3', 'urbanización la gruta 7',
       'av mompia', 'barrio somacueto', 'avenida josé maría de pereda',
       'calle respuela 2', 'calle s cruz-san juan 7', 'barrio la cruz',
       'la calleja', 'barrio portio', 'avenida josé maría de pereda 8',
       'barrio el pozo de la torre 1a', 'barrio el pozo de la torre 1',
       'calle barrio el pozo de la torre 1 distrito mortera 1',
       'avenida josé maría de pereda 6',
       'vía barrio el pozo de la torre 1', 'cl respuela 4',
       'avenida marqués de valdecilla', 'alto san mateo s/n',
       'barrio la cotera 1', 'calle bo las reigadas 12',
       'urbanización ladera sur', 'av san juan de la canal 85',
       'avenida marqués de valdecilla s/n', 'parcela b19',
       'calle el palacio s/n', 'barrio la caseta',
       'urbanización el padrón 1', 'calle la llata', 'cl llata (la)',
       'barrio salas', 'barrio de la cruz s/n',
       'urb. cierro de la sara s/n', 'barrio el dueso',
       'soto de la marina', 'avenida mompía', 'barrio somacueto 4a',
       'calle el sartal', 'avenida s cibrian', 'barrio la piñera 5',
       'bo llatas 1010', 'urbanización arco iris', 'barrio manzanedo',
       'boo', 'avenida menéndez pelayo', 'calle la gesa 6',
       'calle murillo 1', 'jose maria pereda', 'calle ramón ramírez',
       'avenida menéndez pelayo 11', 'barrio san josé', 'calle respuela',
       'marina sport 5', 'avenida josé maría de pereda 12',
       'urbanización la roca', 'barrio san josé 2', 'barrio la piñera 16',
       'sancibrián', 'bezana 1', 'calle de borrancho', 'respuela 4',
       'calle mies de domañas 98', 'calle gertrudis gómez avellaned 1',
       'calle san felipe neri 49', 'calle la fuente 2',
       'hermanos calderón 20', 'calle bellavista 5', 'calle udial 1',
       'calle gertrudis gómez 5', 'bº argomilla 5',
       'avenida monseñor del val 13', 'carretera ca-135 6',
       'calle mies de domañas 132', 'alto de pedroa s/n',
       'calle cam. del bao 2', 'calle joaquín fernández san emeterio 14',
       'bo. quintana 268', 'calle ojáiz s/n', 'calle manel vélez 14',
       'vía barrio el canal 14', 'avenida de cantabria 60', 'general 181',
       'calle mijares 21', 'manuel vélez 10', 'josé ortega y gasset 39',
       'calle la central 21', 'calle el millajo 46', 'barrio casar 253',
       'avenida joaquín ortiz de zárate 99',
       'calle de victoriano fernández 16', 'calle aldea 24',
       'calle carmen bravo villasante / calle santiago garcía cuadrado 3',
       'calle ricardo bernardo 1', 'calle castío 1',
       'calle menéndez pelayo 13', 'la hayuela s/n',
       'calle piedra del cormorán s/n', 'calle el peñón s/n',
       'avenida alfonso viii s/n', 'ayuntamientos democráticos 46',
       'joaquín ferna 1', 'barrio requejada 33', 'calle alcarite s/n',
       'calle torres quevedo 7', 'calle abad paterno 18',
       'barrio la canal 15', 'calle consolación 24', 'calle la central 1',
       'calle barrio el pozo de la torre 1, distrito mortera 1',
       'calle barrio yuso 10', 'paseo de la barquera 53a', 'calle aro 3',
       'calle de la maza 9', 'lugar barrio bádames 1018',
       'calle san juan 7', 'calle bo sámano-helguera 205',
       'los tranquilos 3', 'avenida de españa 29',
       'vía barrio brazomar 36', 'calle jaime del amo 8',
       'calle josé posada herrera 10', 'barrio islares 41',
       'calle barrio las escuelas 35', 'calle pedro sobrado pintor s/n',
       'barrio la rañada 14', 'calle la central 4', 'calle bº ladredo 75',
       'calle barrio bolado 8', 'bº cubas 18',
       'calle padre ignacio ellacuría 163', 'ernest lluch s/n'],
      dtype=object)

In [39]:
df[df["subtipo"].isna()]

,id_anuncio,fuente,operacion,tipo_inmueble,subtipo,direccion_texto,barrio_zona,municipio,provincia,precio_eur,...,garaje_incluido,habitaciones,superficie_m2,planta,exterior,ascensor,obra_nueva_categoria,obra_nueva_flag,notas_parseo,descuento_flag
575,Inmobiliaria JC de Laredo,venta,finca_rustica,barrio rocillo,NaN,Ampuero,Cantabria,320000,NaN,NaN,...,3.0,220,NaN,NaN,NaN,NaN,0,Licencia turística 7 plazas (texto),NaN,0
577,Inmobiliaria Mi Villa,venta,finca_rustica,n-629a,NaN,Rasines,Cantabria,89000,NaN,NaN,...,1.0,300,NaN,NaN,NaN,NaN,0,Casa piedra; parcela 6000 m2 (texto),NaN,0
584,Inmobiliaria Mi Villa,venta,finca_rustica,camino de solorga,NaN,Bareyo,Cantabria,300000,NaN,NaN,...,3.0,200,NaN,NaN,NaN,NaN,0,Dos casas; 38590 m2 (texto),NaN,0

In [40]:
df["tipo_inmueble"] = df["tipo_inmueble"].fillna("casa independiente")

In [41]:
df["direccion_texto"] = (
    df["direccion_texto"]
        .astype(str)
        .str.strip()                  # elimina espacios inicio y final
        .str.strip('"')               # elimina comillas dobles inicio y final
        .str.strip("'")               # elimina comillas simples si hubiera
        .str.strip()                  # limpia otra vez por seguridad
)

In [42]:
df.head(20)

,id_anuncio,fuente,operacion,tipo_inmueble,subtipo,direccion_texto,barrio_zona,municipio,provincia,precio_eur,...,garaje_incluido,habitaciones,superficie_m2,planta,exterior,ascensor,obra_nueva_categoria,obra_nueva_flag,notas_parseo,descuento_flag
1,Inmobiliaria E-Castro,venta,piso,casa independiente,"""avenida riomar",1,Cotolino,Castro-Urdiales,Cantabria,498000,...,1.0,4,121,4.0,1.0,1.0,otros,0,NaN,0
2,Inmobiliarias.com,venta,casa,chalét independiente,"barrio brazomar, 46",Cotolino,Castro-Urdiales,Cantabria,575000,NaN,...,5.0,232,NaN,NaN,NaN,NaN,0,NaN,NaN,1
3,Inmobiliaria E-Castro,venta,piso,casa independiente,"""calle leonardo rucabado",6,Centro,Castro-Urdiales,Cantabria,299000,...,NaN,2,84,3.0,1.0,1.0,otros,0,Garaje no indicado,0
4,Inmobiliaria E-Castro,venta,piso,casa independiente,"""calle de la ronda",32,Centro,Castro-Urdiales,Cantabria,340000,...,NaN,4,99,5.0,1.0,1.0,otros,0,Garaje no indicado,0
5,Inmobiliaria E-Castro,venta,casa,chalét independiente,barrio sámano,Sámano,Castro-Urdiales,Cantabria,799000,NaN,...,5.0,511,NaN,NaN,NaN,NaN,0,Dirección sin número,NaN,1
6,Inmobiliarias.com,venta,ático,casa independiente,"""calle de angel perez hornoas cholo""",Brazomar,Castro-Urdiales,Cantabria,360000,NaN,...,3.0,130,6,NaN,1.0,NaN,0,NaN,NaN,1
7,Inmobiliarias.com,venta,ático,casa independiente,"""calle de la granja""",Cotolino,Castro-Urdiales,Cantabria,405000,NaN,...,2.0,90,4,NaN,1.0,NaN,0,NaN,NaN,1
8,Inmobiliarias.com,venta,piso,casa independiente,"""calle ataúlfo argenta""",Cotolino,Castro-Urdiales,Cantabria,415000,NaN,...,3.0,110,2,NaN,1.0,NaN,0,NaN,NaN,1
9,Inmobiliarias.com,venta,casa,chalét independiente,barrio montealegre,Sámano,Castro-Urdiales,Cantabria,455000,NaN,...,5.0,266,NaN,NaN,NaN,NaN,0,Garaje no indicado,NaN,1
10,Inmobiliaria E-Castro,venta,piso,casa independiente,"""isaac castillo""",Mioño-Santullán,Castro-Urdiales,Cantabria,180000,NaN,...,4.0,105,1,NaN,0.0,NaN,0,NaN,NaN,1
11,Exclusivas Inmobiliarias Mikeli,venta,dúplex,casa independiente,"""calle doctor marañón""",El Sardinero,Santander,Cantabria,2890000,NaN,...,4.0,310,2,NaN,1.0,NaN,0,NaN,NaN,1
12,Exclusivas Inmobiliarias Mikeli,venta,piso,casa independiente,"""avenida manuel garcía lago""",El Sardinero,Santander,Cantabria,3150000,NaN,...,5.0,241,4,NaN,1.0,NaN,0,NaN,NaN,1
13,Inmobiliaria E-Castro,venta,piso,casa independiente,"""calle leonardo rucabado""",Centro,Castro-Urdiales,Cantabria,220000,NaN,...,2.0,64,6,NaN,1.0,NaN,0,Dirección sin número,NaN,1
14,Inmobiliarias.com,venta,casa,chalét independiente,barrio cerdigo,Oriñón-Allendagua,Castro-Urdiales,Cantabria,370000,NaN,...,4.0,227,NaN,NaN,NaN,NaN,0,NaN,NaN,1
15,Exclusivas Inmobiliarias Mikeli,venta,piso,casa independiente,"""avenida maura""",El Sardinero,Santander,Cantabria,520000,NaN,...,2.0,105,1,NaN,1.0,NaN,0,NaN,NaN,1
16,Exclusivas Inmobiliarias Mikeli,venta,piso,casa independiente,"""avenida de cantabria""",Valdenoja,Santander,Cantabria,798000,860000,...,3.0,178,3,NaN,1.0,NaN,0,En el texto indica edificio construido en 2005,NaN,1
17,Inmobiliarias.com,venta,casa,chalét adosado,calle del alto de la cruz,Cotolino,Castro-Urdiales,Cantabria,450000,NaN,...,4.0,250,NaN,NaN,NaN,NaN,0,NaN,NaN,1
18,Exclusivas Inmobiliarias Mikeli,venta,piso,casa independiente,"""paseo de pereda""",Puerto Chico,Santander,Cantabria,1800000,NaN,...,5.0,292,4,NaN,0.0,NaN,0,Garaje no indicado,NaN,1
19,Exclusivas Inmobiliarias Mikeli,venta,casa,chalét independiente,barrio la arnía,Liencres,Piélagos,Cantabria,875000,NaN,...,6.0,308,NaN,NaN,NaN,NaN,0,NaN,NaN,1
20,Engel & Völkers Santander,venta,piso,casa independiente,"""avenida de pontejos""",El Sardinero,Santander,Cantabria,885000,NaN,...,4.0,189,8,NaN,1.0,NaN,0,NaN,NaN,1

In [43]:
cols_numericas = [
    "precio_eur",
    "precio_anterior_eur",
    "superficie_m2",
    "habitaciones",
    "planta",
    "descuento_pct"
]

for col in cols_numericas:
    df[col] = pd.to_numeric(df[col], errors="coerce")

for col in cols_numericas:
    print(col, df[col].isna().sum())

precio_eur 789
precio_anterior_eur 796
superficie_m2 176
habitaciones 100
planta 518
descuento_pct 861

In [44]:
df = df[df["precio_eur"].notna()]

In [45]:
df["precio_eur"].isna().sum()

0

In [46]:
df[cols_numericas].dtypes

precio_eur             float64
precio_anterior_eur    float64
superficie_m2          float64
habitaciones           float64
planta                 float64
descuento_pct          float64
dtype: object

In [47]:
df.dtypes

id_anuncio               object
fuente                   object
operacion                object
tipo_inmueble            object
subtipo                  object
direccion_texto          object
barrio_zona              object
municipio                object
provincia                object
precio_eur              float64
precio_anterior_eur     float64
descuento_pct           float64
garaje_incluido         float64
habitaciones            float64
superficie_m2           float64
planta                  float64
exterior                float64
ascensor                float64
obra_nueva_categoria     object
obra_nueva_flag          object
notas_parseo             object
descuento_flag            int32
dtype: object

In [48]:
df.head(20)

,id_anuncio,fuente,operacion,tipo_inmueble,subtipo,direccion_texto,barrio_zona,municipio,provincia,precio_eur,...,garaje_incluido,habitaciones,superficie_m2,planta,exterior,ascensor,obra_nueva_categoria,obra_nueva_flag,notas_parseo,descuento_flag
1,Inmobiliaria E-Castro,venta,piso,casa independiente,"""avenida riomar",1,Cotolino,Castro-Urdiales,Cantabria,498000.0,...,1.0,4.0,121.0,4.0,1.0,1.0,otros,0,NaN,0
3,Inmobiliaria E-Castro,venta,piso,casa independiente,"""calle leonardo rucabado",6,Centro,Castro-Urdiales,Cantabria,299000.0,...,NaN,2.0,84.0,3.0,1.0,1.0,otros,0,Garaje no indicado,0
4,Inmobiliaria E-Castro,venta,piso,casa independiente,"""calle de la ronda",32,Centro,Castro-Urdiales,Cantabria,340000.0,...,NaN,4.0,99.0,5.0,1.0,1.0,otros,0,Garaje no indicado,0
16,Exclusivas Inmobiliarias Mikeli,venta,piso,casa independiente,"""avenida de cantabria""",Valdenoja,Santander,Cantabria,798000,860000.0,...,3.0,178.0,3.0,NaN,1.0,NaN,0,En el texto indica edificio construido en 2005,NaN,1
23,Inmobiliarias.com,venta,piso,casa independiente,"""calle belén",3,Centro,Castro-Urdiales,Cantabria,430000.0,...,NaN,2.0,84.0,2.0,1.0,1.0,otros,0,Indica 'reciente construcción' pero no 'obra n...,0
24,Inmobiliaria E-Castro,venta,piso,casa independiente,"""calle leonardo rucabado",50,Brazomar,Castro-Urdiales,Cantabria,270000.0,...,1.0,2.0,64.0,2.0,1.0,1.0,otros,0,NaN,0
29,Inmobiliarias.com,venta,piso,casa independiente,"""avenida riomar",1,Cotolino,Castro-Urdiales,Cantabria,498000.0,...,1.0,4.0,120.0,4.0,1.0,1.0,otros,0,Duplicado potencial del anuncio #1 (misma dire...,0
35,Inmobiliaria JC de Laredo,venta,piso,casa independiente,centro,Centro,Laredo,Cantabria,580000,620000.0,...,NaN,4.0,240.0,5.0,1.0,1.0,otros,0,Texto lo describe como ático dúplex,1
41,Trece Home,venta,piso,casa independiente,calle peredo y nogales,Tregadín,Noja,Cantabria,269000,279000.0,...,NaN,2.0,75.0,0.0,NaN,1.0,otros,0,NaN,1
59,Inmobiliaria Uranga,venta,casa,chalét pareado,avenida de la libertad,Zona Playa,Laredo,Cantabria,385000,398000.0,...,NaN,4.0,180.0,NaN,NaN,NaN,otros,0,Zona Puntal según texto; cabecera pone Zona Playa,1
60,donpiso Santander,venta,piso,casa independiente,calle general moscardó,Castilla - Hermida,Santander,Cantabria,159000,165000.0,...,NaN,3.0,68.0,3.0,1.0,1.0,otros,0,Vivienda a reformar (texto),1
61,Inmobiliaria Eurocasa,venta,piso,casa independiente,calle tetuán,General Dávila,Santander,Cantabria,335000,350000.0,...,NaN,3.0,83.0,2.0,1.0,1.0,otros,0,NaN,1
69,Inmosantander,venta,dúplex,casa independiente,av cantabria,Valdenoja,Santander,Cantabria,695000,720000.0,...,NaN,4.0,176.0,4.0,1.0,1.0,otros,0,Construida en 2008 (texto),1
87,Inmobiliaria E-Castro,venta,piso,casa independiente,calle bajada del chorrillo 8,Centro,Castro-Urdiales,Cantabria,235000,249000.0,...,NaN,2.0,91.0,2.0,1.0,1.0,otros,0,Vivienda con inquilino (texto),1
90,Exclusivas inmobiliarias mikeli,venta,dúplex,casa independiente,paseo menéndez pelayo,General Dávila,Santander,Cantabria,530000,580000.0,...,NaN,4.0,162.0,NaN,1.0,0.0,otros,0,Planta no indicada; dice exterior sin ascensor,1
99,Inmobiliarias.com,venta,casa,casa independiente,carretera mioño,Mioño-Santullán,Castro-Urdiales,Cantabria,360000,370000.0,...,NaN,3.0,160.0,NaN,NaN,NaN,otros,0,Garaje no indicado,1
114,Inmobiliaria E-Castro,venta,piso,casa independiente,calle la rúa,Centro,Castro-Urdiales,Cantabria,160000,196000.0,...,NaN,4.0,143.0,2.0,1.0,0.0,otros,0,NaN,1
147,Inmobiliaria Uranga,venta,piso,casa independiente,calle república de colombia,Zona Playa,Laredo,Cantabria,240000,250000.0,...,NaN,2.0,60.0,15.0,1.0,1.0,otros,0,Garaje no indicado,1
158,altamira21.com,venta,piso,casa independiente,calle san sebastian,General Dávila,Santander,Cantabria,209000,215000.0,...,NaN,2.0,55.0,3.0,1.0,0.0,otros,0,Reformado,1
202,Exclusivas inmobiliarias mikeli,venta,casa,chalét pareado,calle vicente trueba 3,Alisal - Cazoña - San Román,Santander,Cantabria,475000,495000.0,...,NaN,4.0,228.0,NaN,NaN,NaN,otros,0,NaN,1